{|
typedef GtkNotebook * GtkNotebook_ptr;
typedef GtkNotebookClass * GtkNotebookClass_ptr;
typedef GtkNotebookPage * GtkNotebookPage_ptr;
|}

typedef [abstract, mltype(gtk_object)] GtkWidget * GtkWidget_ptr;
typedef [abstract, mltype(gtk_object)] GtkNotebook * GtkNotebook_ptr;
typedef [abstract, mltype(gtk_object)] GtkNotebookClass * GtkNotebookClass_ptr;
typedef [abstract, mltype(gtk_object)] GtkNotebookPage * GtkNotebookPage_ptr;
typedef int GtkPositionType;

// replace \(Gtk[a-zA-z]*\) +\* by \1_ptr 
// replace guint by unsigned int
// replace gint by int

unsigned int      gtk_notebook_get_type        (void);
GtkWidget_ptr     gtk_notebook_new             (void);
void       gtk_notebook_append_page       (GtkNotebook_ptr notebook,
				           GtkWidget_ptr child,
				           GtkWidget_ptr tab_label)
	{| /* sanity checks */
           gtk_notebook_append_page(notebook, child, tab_label);
        |};
void       gtk_notebook_append_page_menu  (GtkNotebook_ptr notebook,
					   GtkWidget_ptr child,
					   GtkWidget_ptr tab_label,
					   GtkWidget_ptr menu_label);
void       gtk_notebook_prepend_page      (GtkNotebook_ptr notebook,
				           GtkWidget_ptr child,
				           GtkWidget_ptr tab_label);
void       gtk_notebook_prepend_page_menu (GtkNotebook_ptr notebook,
					   GtkWidget_ptr child,
					   GtkWidget_ptr tab_label,
					   GtkWidget_ptr menu_label);
void       gtk_notebook_insert_page       (GtkNotebook_ptr notebook,
				           GtkWidget_ptr child,
				           GtkWidget_ptr tab_label,
				           int              position);
void       gtk_notebook_insert_page_menu  (GtkNotebook_ptr notebook,
				           GtkWidget_ptr child,
				           GtkWidget_ptr tab_label,
					   GtkWidget_ptr menu_label,
				           int              position);
void       gtk_notebook_remove_page       (GtkNotebook_ptr notebook,
				           int              page_num);
int       gtk_notebook_current_page      (GtkNotebook_ptr notebook);
void       gtk_notebook_set_page          (GtkNotebook_ptr notebook,
				           int              page_num);
void       gtk_notebook_next_page         (GtkNotebook_ptr notebook);
void       gtk_notebook_prev_page         (GtkNotebook_ptr notebook);
void       gtk_notebook_set_tab_pos       (GtkNotebook_ptr notebook,
					   GtkPositionType   pos);
void       gtk_notebook_set_show_tabs     (GtkNotebook_ptr notebook,
					   int              show_tabs);
void       gtk_notebook_set_show_border   (GtkNotebook_ptr notebook,
					   int              show_border);
void       gtk_notebook_set_scrollable    (GtkNotebook_ptr notebook,
					   int              scrollable);
void       gtk_notebook_set_tab_border    (GtkNotebook_ptr notebook,
					   int              border_width);
void       gtk_notebook_popup_enable      (GtkNotebook_ptr notebook);
void       gtk_notebook_popup_disable     (GtkNotebook_ptr notebook);
