include ..\Makefile.config

CC=cl
CFLAGS=/nologo /Zi /MT /I$(OCAMLLIB)

OBJS=idlalloc.obj comintf.obj cfactory.obj comerror.obj superror.obj \
  registry.obj

all: camlidlruntime.lib

camlidlruntime.lib: $(OBJS)
	- rm -f $@
	lib /nologo /debugtype:CV /out:$@ $(OBJS)

.SUFFIXES: .c .cpp .obj

.c.obj:
	$(CC) $(CFLAGS) -c $*.c
.cpp.obj:
	$(CC) $(CFLAGS) -c $*.cpp

$(OBJS): camlidlruntime.h comstuff.h registry.h
