include ..\Makefile.config

OCAMLC=ocamlc

OBJS=idlalloc.obj comintf.obj cfactory.obj

all: camlidlruntime.lib

camlidlruntime.lib: $(OBJS)
	- rm -f $@
	lib /nologo /debugtype:CV /out:$@ $(OBJS)

.SUFFIXES: .c .obj

.c.obj:
	$(OCAMLC) -ccopt "$(CFLAGS)" $*.c

depend:
	gcc -I$(OCAMLLIB) -MM *.c > .depend

include .depend



