include ../Makefile.config

OCAMLC=ocamlc

OBJS=idlalloc.o comintf.o cfactory.o comerror.o

all: camlidlruntime.a

camlidlruntime.a: $(OBJS)
	- rm -f $@
	ar rc $@ $(OBJS)
	$(RANLIB) $@

install:
	cp camlidlruntime.h $(OCAMLLIB)/caml/camlidlruntime.h
	cp camlidlruntime.a $(OCAMLLIB)/camlidlruntime.a
	cd $(OCAMLLIB); $(RANLIB) camlidlruntime.a

clean:
	rm -f *.a *.o

.SUFFIXES: .c .o

.c.o:
	$(OCAMLC) -ccopt "$(CFLAGS)" $*.c

depend:
	gcc -I$(OCAMLLIB) -MM *.c > .depend

include .depend



