## Configuration section

# Type of system
# OSTYPE=unix
OSTYPE=win32

# How to invoke the C preprocessor
# CPP=/lib/cpp
# Alternatives:
# CPP=/usr/bin/cpp
# CPP=gcc -x c -E
CPP=cl /nologo /E

# How to invoke ranlib (only relevant for Unix)
#RANLIB=ranlib
# If ranlib is not needed:
#RANLIB=:

# Location of the Objective Caml library in your installation
OCAMLLIB=/ocaml/lib

# The Objective Caml compilers (the defaults below should be OK)
OCAMLC=ocamlc -g
OCAMLDEP=ocamldep
OCAMLYACC=ocamlyacc -v
OCAMLLEX=ocamllex

# Extra flags to pass to cc
CFLAGS=/Zi
