#
# Chapter 7 - Makefile
#
#
# Flags - Always compiles debug.
#
CPP_FLAGS=/c /MTd /Zi /Od /D_DEBUG
EXE_LINK_FLAGS=/DEBUG
DLL_LINK_FLAGS=/DLL /DEBUG

LIBS=UUID.lib Advapi32.lib Ole32.lib

#################################################
#
# Targets
#
all : client component camlclient camlcomponent

client : Client.exe 

component : Cmpnt.dll 
	   

#################################################
#
# Shared source files
#

GUIDs.obj : GUIDs.cpp 
	cl $(CPP_FLAGS) GUIDs.cpp

Registry.obj : Registry.cpp Registry.h
	cl $(CPP_FLAGS) Registry.cpp

#################################################
#
# component source files
#

Cmpnt.obj : Cmpnt.cpp Iface.h Registry.h
	cl $(CPP_FLAGS) Cmpnt.cpp


#################################################
#
# Client source files
#

Client.obj : Client.cpp Iface.h 
	cl $(CPP_FLAGS) Client.cpp


#################################################
#
# Link component and automatically register component.
#

Cmpnt.dll : Cmpnt.obj	GUIDs.obj Registry.obj Cmpnt.def 
	link $(DLL_LINK_FLAGS) Cmpnt.obj GUIDs.obj Registry.obj $(LIBS) /DEF:Cmpnt.def 
	regsvr32 -s Cmpnt.dll

#################################################
#
# Link client.
#

Client.exe : Client.obj GUIDs.obj
	link $(EXE_LINK_FLAGS) Client.obj GUIDs.obj $(LIBS)

#############
#
# Caml side
#
camlclient : camlclient.exe

camlclient.exe: component.obj GUIDs.obj component.cmo camlclient.cmo
	ocamlc -ccopt /Zi -o camlclient.exe  -custom -I ../.. \
          com.cmo component.cmo camlclient.cmo \
          component.obj GUIDs.obj \
          ../../runtime/camlidlruntime.lib oleaut32.lib ole32.lib

component.ml component.mli component.c: component.idl ../../compiler/camlidl
	../../compiler/camlidl -header component.idl

component.cmo: component.ml component.cmi
component.cmi: component.mli
camlclient.cmo: component.cmi

camlcomponent: camlcomp.dll

camlcomp.dll: component.obj GUIDs.obj camlcomp.obj camlcomp.def
	link /nologo /incremental:no /dll /out:camlcomp.dll /def:camlcomp.def \
          camlcomp.obj component.obj GUIDs.obj \
          ..\..\runtime\cfactory.obj \
          ..\..\runtime\camlidlruntime.lib \
          \ocaml\lib\libcamlrun.lib \
          ole32.lib oleaut32.lib advapi32.lib
	regsvr32 -s Cmpnt.dll

camlcomp.obj: component.cmo camlcomp.cmo camlcomp.cmo
	ocamlc -ccopt /Zi -output-obj -o camlcomp.obj -custom -I ../.. \
          com.cmo component.cmo camlcomp.cmo

camlcomp.cmo: component.cmi

.SUFFIXES: .ml .mli .cmo .cmi .c .obj

.ml.cmo:
	ocamlc -I ../.. -c $<

.mli.cmi:
	ocamlc -I ../.. -c $<

.c.obj:
	ocamlc -ccopt /Zi -c $<

camlcomponent:
